version: "0.0.5.0"

safety_timeout: 5.0 # [s]

main_timer_rate: 30 # [Hz]

channel_number: 6

# after landing and after this timeout, the computer will be shut down
shutdown_timeout: 120 # [s]

# how many times it will try to call the start/stop services if it fails
call_n_attempts: 10

challenges:

  balloons:

    handle_takeoff: true
    handle_landing: true
    action_duration: 12.0 # [min]
    land_mode: "eland" # {land_home, land_there, land, eland}
    pre_takeoff_sleep: 15 # [s]

  ball:

    handle_takeoff: true
    handle_landing: true
    action_duration: 8.0 # [min]
    land_mode: "land_there" # {land_home, land_there, land, eland}
    pre_takeoff_sleep: 0 # [s]

  wall:

    handle_takeoff: false
    handle_landing: false
    action_duration: 10.0 # [min]
    land_mode: "eland" # {land_home, land_there, land, eland}
    pre_takeoff_sleep: 0 # [s]

  fire:

    handle_takeoff: true
    handle_landing: false
    action_duration: 8.0 # [min]
    land_mode: "eland" # {land_home, land_there, land, eland}
    pre_takeoff_sleep: 0 # [s]

  fire_indoor:

    handle_takeoff: true
    handle_landing: false
    action_duration: 8.0 # [min]
    land_mode: "eland" # {land_home, land_there, land, eland}
    pre_takeoff_sleep: 0 # [s]

  blanket:

    handle_takeoff: true
    handle_landing: false
    action_duration: 12.0 # [min]
    land_mode: "eland" # {land_home, land_there, land, eland}
    pre_takeoff_sleep: 0 # [s]
