version: "0.0.5.0"

safety_timeout: 5.0 # [s]

main_timer_rate: 30 # [Hz]

# how many times it will try to call the start/stop services if it fails
call_n_attempts: 10

handle_takeoff: true
handle_landing: false
action_duration: 12.0 # [min]
land_mode: "eland" # {land_home, land, eland}
pre_takeoff_sleep: 0 # [s]
