# Set receivers to "all" or list of machines:
# -> receivers: ["all"]
# -> receivers: ["uav1", "uav2", "uav3"]

receivers: ["all"] 
# receivers: ["uav7", "uav8"]

topics: # topics published out of this machine to receivers specified above
 - name: "control_manager/mpc_tracker/predicted_trajectory"
   compress: false # enable bz2 compression
   rate: 2.0 # rate limit at 5Hz
 - name: "odometry/slow_odom"
   compress: false # enable bz2 compression
   rate: 1.0

services:
  - name: "/*/odometry/change_estimator_type_string"
    type: mrs_msgs/String 
  - name: "/*/control_manager/motors"
    type: std_srvs/SetBool 
  - name: "/*/uav_manager/takeoff"
    type: std_srvs/Trigger 
  - name: "/*/uav_manager/land"
    type: std_srvs/Trigger 


