trajectory_folder: "/home/mrs/git/uav_modules/ros_packages/trajectory_loader/sample_trajectories"
trajectory_files: ["trajectory1.txt", "trajectory2.txt", "circle_10_5.txt", "eight_8ms.txt"]

trajectory_dt: 0.2 # (s)
min_mutual_distance: 5.5 # (m)

constraints: "slow"

visualization_rviz: 
  use: True
  playback_speed: 10.0

visualization_python:
  trajectories: True
  dynamics: True
  mutual_distance: True

print_info: True

safety_area:
  min_height: 1.0
  max_height: 30.0
