uavs_ip_addresses: ["uav1", "192.168.0.101",
                    "uav2", "192.168.0.102",
                    "uav3", "192.168.0.103",
                    "uav4", "192.168.0.104",
                    "uav5", "192.168.0.105",
                    "uav41", "192.168.0.141"]
