uavs_ip_addresses: ["uav1", "192.168.0.101",
                    "uav2", "192.168.0.102",
                    "uav3", "192.168.0.103",
                    "uav4", "192.168.0.104",
                    "uav5", "192.168.0.105",
                    "uav6", "192.168.0.106",
                    "uav7", "192.168.0.107",
                    "uav8", "192.168.0.108",
                    "uav9", "192.168.0.109",
                    "uav10", "192.168.0.110",
                    "uav11", "192.168.0.111",
                    "uav41", "192.168.0.141",
                    "uav42", "192.168.0.142",
                    "vojta", "192.168.0.5",
                    "uav60", "192.168.0.160"]
