#
## DEFINITION OF THE ARENA
#
 
use_home_position: true

home_utm_x: 465710.758973
home_utm_y: 5249465.43086

safety_area:

  use_safety_area: true

  # convex polygon CCW
  safety_area: [-50, -50,
  50, -50,
  50, 50,
  -50, 50]

  max_height: 20.0
  min_height: 1.0
