#
## DEFINITION OF THE ARENA
#
 
use_home_position: true

home_utm_x: 428789.2
home_utm_y: 5480811.2

use_safety_area: true

<<<<<<< HEAD
safety_area: [-20.0, -26.5,
41.0, -44.0,
61.0, 40.0,
-60.0, 55.0]
=======
-safety_area: [60.0, 45.0,
--72.0, 56.0,
--47.0, -11.5,
-41.0, -39.0]

>>>>>>> cvxgenXY2
