#
## DEFINITION OF THE ARENA
#
 
use_utm_origin: true
utm_origin_x: 465710.758973
utm_origin_y: 5249465.43086

use_local_origin: false
local_origin_x: 5.0
local_origin_y: 3.0

safety_area:

  use_safety_area: false

  # convex polygon CCW
  safety_area: [-50, -50,
  50, -50,
  50, 50,
  -50, 50]

  max_height: 20.0
  min_height: 1.0
