#
## DEFINITION OF THE ARENA
#
 
use_utm_origin: true
utm_origin_x: 429426.45
utm_origin_y: 5492357.99

use_local_origin: false
local_origin_x: 0.0
local_origin_y: 0.0

safety_area:

  use_safety_area: true

  # convex polygon CCW
  safety_area: [-100.0, -80.0,                                                                         
  -10.0, -80.0,                                                                                        
  -21.0, -28.0,                                                                                        
  -90.0, -23.0]

  max_height: 10.0
  min_height: 1.0
