#
## DEFINITION OF THE ARENA
#
 
use_home_position: true

home_utm_x: 429426.45
home_utm_y: 5492357.99

use_safety_area: true

#
## Leave just one of the following arenas uncommented
#

## Field only arena LEFT to the electricity
safety_area: [-100.0, -80.0,                                                                         
-10.0, -80.0,                                                                                        
-21.0, -28.0,                                                                                        
-90.0, -23.0]


