#
## DEFINITION OF THE ARENA
#

use_utm_origin: false
utm_origin_x: 0
utm_origin_y: 0

use_local_origin: true
local_origin_x: 0.0
local_origin_y: 0.0

safety_area:

  use_safety_area: true

  # convex polygon CCW
  safety_area: [-2, -2,
  2, -2,
  2, 2,
  -2, 2]

  max_height: 2.0
  min_height: 0.5
