#
## DEFINITION OF THE ARENA
#
 
use_utm_origin: true
utm_origin_units: 1 # 0 - UTM, 1 - Latitude Longitude
utm_origin_lat: 24.132579
utm_origin_lon: 55.332417
utm_origin_x: 0
utm_origin_y: 0

use_local_origin: true
local_origin_x: 0.0
local_origin_y: 0.0

safety_area:

  use_safety_area: true

  frame_name: "latlon_origin"

  polygon_obstacles:
    # loaded as a vector of matrices
    # each matrix has polygon vertices in columns
    # [[M1], [M2]]
    enabled: false
    data: [1, 10, 10, 1,    5, 8, 5,
           1, 1, 10, 10,    5, 5, 8,]
    rows: 2 # each matrix has two rows
    cols: [4, 3] # nums of cols of each matrix

  point_obstacles:
    # loaded as a vector of matrices
    # x, y, radius
    enabled: false
    data: [-5.0, -5.0, 2, # 1st point
           -10.0, -10.0, 4] # 2nd point
    rows: 1 # each matrix has a single row
    cols: [3, 3] # nums of cols of each matrix

  # convex polygon CCW
  # race track
  safety_area: [
    24.1326388, 55.3323408,
    24.1325441, 55.332377,
    24.1326409, 55.3325683,
    24.1327444, 55.3325021,
    ]

  max_height: 8.0
  min_height: 1.0
