#
## DEFINITION OF THE MBZIRC CHALLENGE ARENA
#
 
arena_id: "fire_adnec_after_rehearsal_1"
 
use_utm_origin: true
utm_origin_units: 0 # 0 - UTM, 1 - Latitude Longitude
utm_origin_lat: 0
utm_origin_lon: 0
utm_origin_x: 240069.61
utm_origin_y: 2702863.31

use_local_origin: false
local_origin_x: 0.0
local_origin_y: 0.0

safety_area:

  use_safety_area: false

  frame_name: "gps_origin"

  polygon_obstacles:
    # loaded as a vector of matrices
    # each matrix has polygon vertices in columns
    # [[M1], [M2]]
    enabled: false
    data: [1, 10, 10, 1,    5, 8, 5,
           1, 1, 10, 10,    5, 5, 8,]
    rows: 2 # each matrix has two rows
    cols: [4, 3] # nums of cols of each matrix

  point_obstacles:
    # loaded as a vector of matrices
    # x, y, radius
    enabled: false
    data: [-5.0, -5.0, 2, # 1st point
           -10.0, -10.0, 4] # 2nd point
    rows: 1 # each matrix has a single row
    cols: [3, 3] # nums of cols of each matrix

  # convex polygon CCW
  # race track
  safety_area: [
    -15.45, -17.78,
    28.44, -31.56,
    29.51, -28.70,
    34.55, -30.23,
    42.22, -5.10,
    38.20, -3.26,
    40.02, 1.81,
    -4.19, 14.71,
    -5.59, 10.63,
    -9.62, 12.04,
    -18.13, -14.41,
    -15.10, -15.24]

  max_height: 18.00
  min_height: 0.30


arena_ang_diff: -0.304211
arena_center: [12.20, -8.12]
arena_corners: [
  -18.87, -16.71, # K
  33.65, -33.19, # L
  43.98, 0.65, # M
  -8.37, 15.93] # N

takeoff_center: [8.00, -22.00]
takeoff_zone: [
  -2.29, -21.39,
  16.79, -27.38,
  18.29, -22.61,
  -0.79, -16.62]

arena_type: 'fire_arena'

ground_floor_floor: 0.00
ground_floor_ceiling: 4.80
ground_floor_center: [23.99, -12.95]
ground_floor_outside_points: [
  9.75, -16.14,
  34.18, -23.24,
  38.08, -9.79,
  13.95, -2.81]

first_floor_floor: 5.00
first_floor_ceiling: 9.80
first_floor_center: [18.11, -11.26]
first_floor_outside_points: [
  9.75, -16.14,
  22.27, -19.70,
  26.68, -6.26,
  13.95, -2.81]

second_floor_floor: 10.00
second_floor_ceiling: 14.80
second_floor_center: [18.11, -11.26]
second_floor_outside_points: [
  9.75, -16.14,
  22.27, -19.70,
  26.68, -6.26,
  13.95, -2.81]

fires_outdoor: [
  22.58, -18.73, 13.20,
  22.65, -18.51, 8.50,
  24.38, -13.25, 11.00,
  26.50, -6.79, 13.20,
  26.15, -7.87, 5.90,
  25.98, -6.07, 1.00,
  24.83, -5.76, 13.26,
  19.87, -4.41, 10.90,
  15.04, -3.10, 13.30,
  14.96, -3.08, 6.00,
  13.65, -3.77, 3.30,
  13.56, -4.05, 10.65,
  12.37, -7.82, 11.00,
  10.36, -14.20, 13.60,
  10.27, -14.49, 6.38]

windows: [
  14.10, -17.38, 12.60,
  14.10, -17.38, 7.26,
  17.94, -18.47, 12.60,
  17.94, -18.47, 7.26,
  23.80, -15.03, 12.60,
  23.80, -15.03, 7.26,
  25.15, -10.90, 12.60,
  25.15, -10.90, 7.26,
  22.25, -5.06, 12.60,
  22.25, -5.06, 7.26,
  18.35, -4.00, 12.60,
  18.35, -4.00, 7.26,
  12.49, -7.44, 12.60,
  12.49, -7.44, 7.26,
  11.20, -11.53, 12.60,
  11.20, -11.53, 7.26]
