#
## DEFINITION OF THE ARENA
#
 
use_home_position: true

home_utm_x: 429426.45
home_utm_y: 5492357.99

safety_area:

  use_safety_area: true

  # convex polygon CCW
  safety_area: [-100.0, -80.0,                                                                         
  -10.0, -80.0,                                                                                        
  -21.0, -28.0,                                                                                        
  -90.0, -23.0]

  max_altitude: 10.0
  min_altitude: 1.0
