#
## DEFINITION OF THE MBZIRC CHALLENGE ARENA
#
 
arena_id: "ball_adnec_whole"
 
use_utm_origin: true
utm_origin_units: 0 # 0 - UTM, 1 - Latitude Longitude
utm_origin_lat: 0
utm_origin_lon: 0
utm_origin_x: 240050.13
utm_origin_y: 2702852.59

use_local_origin: false
local_origin_x: 0.0
local_origin_y: 0.0

safety_area:

  use_safety_area: true

  frame_name: "gps_origin"

  polygon_obstacles:
    # loaded as a vector of matrices
    # each matrix has polygon vertices in columns
    # [[M1], [M2]]
    enabled: false
    data: [1, 10, 10, 1,    5, 8, 5,
           1, 1, 10, 10,    5, 5, 8,]
    rows: 2 # each matrix has two rows
    cols: [4, 3] # nums of cols of each matrix

  point_obstacles:
    # loaded as a vector of matrices
    # x, y, radius
    enabled: false
    data: [-5.0, -5.0, 2, # 1st point
           -10.0, -10.0, 4] # 2nd point
    rows: 1 # each matrix has a single row
    cols: [3, 3] # nums of cols of each matrix

  # convex polygon CCW
  # race track
  safety_area: [
    -128.72, 9.03,
    126.53, -72.17,
    134.73, -67.88,
    141.60, -25.89,
    137.70, -16.96,
    -109.45, 62.98,
    -114.60, 58.65,
    -131.64, 15.74]

  max_height: 30.0
  min_height: 1.0


arena_ang_diff: -0.307991
arena_center: [9.27, -4.49]
arena_corners: [
  -133.67, 10.61, # K
  133.66, -74.43, # L
  142.79, -18.60, # M
  -112.49, 63.97] # N

takeoff_center: [0.00, 0.00]
takeoff_zone: [
  -3.14, -1.62,
  1.62, -3.14,
  3.14, 1.62,
  -1.62, 3.14]

arena_type: 'ball_arena'

dropoff_center: [10.00, 0.00]
dropoff_zone: [
  6.86, -1.62,
  11.62, -3.14,
  13.14, 1.62,
  8.38, 3.14]
