#
## DEFINITION OF THE ARENA
#
 
use_utm_origin: true
utm_origin_x: 428789.2
utm_origin_y: 5480811.2

use_local_origin: false
local_origin_x: 0.0
local_origin_y: 0.0

safety_area:

  use_safety_area: true

  # # convex polygon CCW
  # # big area
  # safety_area: [60.0, 45.0,
  # -66.2, 66.8,
  # -27.2, -21.2,
  # 41.0, -39.0]

  # convex polygon CCW
  # small area
  safety_area: [60.0, 45.0,
  -66.2, 66.8,
  -36.0, 6.0,
  46.0, -15.0]


  max_height: 20.0
  min_height: 1.0
