#
## DEFINITION OF THE ARENA
#
 
use_home_position: true

home_utm_x: 429426.45
home_utm_y: 5492357.99

safety_area:

  use_safety_area: true

  # convex polygon CCW
  safety_area: [-17.79, -11.02,
  10.9, -9.02,
  2.9, 16.79,
  -3.65, 10.01]

  max_height: 10.0
  min_height: 1.0
