#
## DEFINITION OF THE ARENA
#
 
use_utm_origin: true
utm_origin_x: 428789.2
utm_origin_y: 5480811.2

use_local_origin: false
local_origin_x: 0.0
local_origin_y: 0.0

safety_area:

  use_safety_area: true

  # convex polygon CCW
  safety_area: [60.0, 45.0,
  -72.0, 56.0,
  -47.0, -11.5,
  41.0, -39.0]

  max_height: 20.0
  min_height: 1.0
