#
## DEFINITION OF THE ARENA
#
 
use_utm_origin: true

# cisar race track
utm_origin_x: 458422.2
utm_origin_y: 5551241.4

# # mezi stromy a lampou
# utm_origin_x: 458383.0
# utm_origin_y: 5551267.0

# # mezi krtinci
# utm_origin_x: 458326
# utm_origin_y: 5551249

use_local_origin: false
local_origin_x: 0.0
local_origin_y: 0.0

safety_area:

  use_safety_area: true

  frame_name: "gps_origin"

  polygon_obstacles:
    # loaded as a vector of matrices
    # each matrix has polygon vertices in columns
    # [[M1], [M2]]
    enabled: false
    data: [1, 10, 10, 1,    5, 8, 5,
           1, 1, 10, 10,    5, 5, 8,]
    rows: 2 # each matrix has two rows
    cols: [4, 3] # nums of cols of each matrix

  point_obstacles:
    # loaded as a vector of matrices
    # x, y, radius
    enabled: false
    data: [-5.0, -5.0, 2, # 1st point
           -10.0, -10.0, 4] # 2nd point
    rows: 1 # each matrix has a single row
    cols: [3, 3] # nums of cols of each matrix

  # convex polygon CCW
  # race track
  safety_area: [30.9, 26.4,
  -45.0, 7.27,
  -31.5, -38.0,
  44.5, -23.5]

  # # convex polygon CCW
  # # race track extended
  # safety_area: [
  # 44.8, -26.4,
  # 31.8, 25.6,
  # -112.2, -0.4,
  # -48.2, -48.4
  # ]
  
  # # convex polygon CCW
  # # mezi stromy a lampou
  # safety_area: [
  # 10.0, 10.0,
  # -10.0, 10.0,
  # -10.0, -10.0,
  # 10.0, -10.0
  # ]

  # # convex polygon CCW
  # # mezi krtinci
  # safety_area: [
  #   -8, -43,
  #   52, -54,
  #   42, 4,
  #   14, 20,
  #   -26, 15,
  #   -32, -26,
  # ]

  max_height: 8.0
  min_height: 1.0
