#
## DEFINITION OF THE MBZIRC CHALLENGE ARENA
#
 
arena_id: "wall_adnec_after_rehearsal_1"
 
use_utm_origin: true
utm_origin_units: 0 # 0 - UTM, 1 - Latitude Longitude
utm_origin_lat: 0
utm_origin_lon: 0
utm_origin_x: 240136.38
utm_origin_y: 2702832.57

use_local_origin: false
local_origin_x: 0.0
local_origin_y: 0.0

safety_area:

  use_safety_area: true

  frame_name: "gps_origin"

  polygon_obstacles:
    # loaded as a vector of matrices
    # each matrix has polygon vertices in columns
    # [[M1], [M2]]
    enabled: false
    data: [1, 10, 10, 1,    5, 8, 5,
           1, 1, 10, 10,    5, 5, 8,]
    rows: 2 # each matrix has two rows
    cols: [4, 3] # nums of cols of each matrix

  point_obstacles:
    # loaded as a vector of matrices
    # x, y, radius
    enabled: false
    data: [-5.0, -5.0, 2, # 1st point
           -10.0, -10.0, 4] # 2nd point
    rows: 1 # each matrix has a single row
    cols: [3, 3] # nums of cols of each matrix

  # convex polygon CCW
  # race track
  safety_area: [
    -22.62, -8.40,
    13.25, -18.81,
    16.93, -17.77,
    25.80, 1.92,
    19.45, 10.90,
    -9.43, 20.94,
    -19.71, 17.10,
    -25.99, -3.01]

  max_height: 30.0
  min_height: 1.0


arena_ang_diff: -0.282316
arena_center: [0.58, 0.35]
arena_corners: [
  -27.26, -7.06, # K
  16.09, -19.63, # L
  28.44, 7.77, # M
  -17.61, 23.79] # N

takeoff_center: [-5.00, -10.00]
takeoff_zone: [
  -15.30, -9.62,
  3.91, -15.19,
  5.30, -10.38,
  -13.91, -4.81]

arena_type: 'wall_arena'

uav_wall_center: [15.00, 5.00]
uav_wall_zone: [
  10.60, 4.19,
  18.28, 1.96,
  19.40, 5.81,
  11.72, 8.04]

uav_brick_center: [-10.00, 5.00]
uav_brick_zone: [
  -13.52, 1.85,
  -8.71, 0.46,
  -6.48, 8.15,
  -11.29, 9.54]

ugv_wall_center: [10.00, -5.00]
ugv_wall_zone: [
  5.60, -5.81,
  13.28, -8.04,
  14.40, -4.19,
  6.72, -1.96]

ugv_brick_center: [-15.00, 0.00]
ugv_brick_zone: [
  -19.26, -0.33,
  -11.58, -2.55,
  -10.74, 0.33,
  -18.42, 2.55]
