#
## DEFINITION OF THE ARENA
#
 
use_utm_origin: true
utm_origin_x: 429426.45
utm_origin_y: 5492357.99

use_local_origin: false
local_origin_x: 0.0
local_origin_y: 0.0

safety_area:

  use_safety_area: true

  # convex polygon CCW
  safety_area: [-7.79, -11.02,
  10.9, -9.02,
  2.9, 16.79,
  -7.65, 16.01]

  max_height: 20.0
  min_height: 1.0
