#
## DEFINITION OF THE ARENA
#
 
use_utm_origin: true
utm_origin_x: 460226.6
utm_origin_y: 5601198.2

use_local_origin: false
local_origin_x: 0.0
local_origin_y: 0.0

safety_area:

  use_safety_area: true

  # convex polygon CCW
  safety_area: [-10, -15,
  20, -15,
  20, 15,
  -10, 15]

  max_height: 8.0
  min_height: 0.5
