#
## DEFINITION OF THE ARENA
#
 
use_home_position: true

home_utm_x: 465710.758973
home_utm_y: 5249465.43086

use_safety_area: true

safety_area: [60.0, 45.0,
-72.0, 56.0,
-47.0, -11.5,
41.0, -39.0]

# safety_area: [-50, -50,
# 50, -50,
# 50, 50,
# -50, 50]
