#
## DEFINITION OF THE MBZIRC CHALLENGE ARENA
#
 
arena_id: "ball_adnec_after_rehearsal_1"
 
use_utm_origin: true
utm_origin_units: 0 # 0 - UTM, 1 - Latitude Longitude
utm_origin_lat: 0
utm_origin_lon: 0
utm_origin_x: 239991.81
utm_origin_y: 2702876.72

use_local_origin: false
local_origin_x: 0.0
local_origin_y: 0.0

safety_area:

  use_safety_area: true

  frame_name: "gps_origin"

  polygon_obstacles:
    # loaded as a vector of matrices
    # each matrix has polygon vertices in columns
    # [[M1], [M2]]
    enabled: false
    data: [1, 10, 10, 1,    5, 8, 5,
           1, 1, 10, 10,    5, 5, 8,]
    rows: 2 # each matrix has two rows
    cols: [4, 3] # nums of cols of each matrix

  point_obstacles:
    # loaded as a vector of matrices
    # x, y, radius
    enabled: false
    data: [-5.0, -5.0, 2, # 1st point
           -10.0, -10.0, 4] # 2nd point
    rows: 1 # each matrix has a single row
    cols: [3, 3] # nums of cols of each matrix

  # convex polygon CCW
  # race track
  safety_area: [
    -38.08, -2.50,
    47.15, -27.94,
    48.90, -27.03,
    56.24, -2.26,
    54.58, 4.14,
    -27.33, 28.30,
    -33.31, 25.58,
    -39.79, 1.88]

  max_height: 30.0
  min_height: 1.0


arena_ang_diff: -0.290063
arena_center: [8.13, 0.72]
arena_corners: [
  -40.76, -1.70, # K
  48.51, -28.34, # L
  57.85, 3.18, # M
  -32.17, 29.73] # N

takeoff_center: [0.00, 0.00]
takeoff_zone: [
  -3.11, -1.68,
  1.68, -3.11,
  3.11, 1.68,
  -1.68, 3.11]

arena_type: 'ball_arena'

dropoff_center: [10.00, 0.00]
dropoff_zone: [
  6.89, -1.68,
  11.68, -3.11,
  13.11, 1.68,
  8.32, 3.11]
